base_url = "https://michaljanocko.com"

title = "Michal JanoÄko"
description = "Michal's personal webpage and blog"

build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

external_links_target_blank = true

[extra]
